Repository dnd-side-project/dnd-5th-5-backend, pull requests merged in 2021-07, with the labels that each got.

#9 [기능] 폴더링
  build.gradle
  src/main/java/com/meme/ala/common/dto/ResponseDto.java
  src/main/java/com/meme/ala/common/message/ResponseMessage.java
  src/main/java/com/meme/ala/core/auth/JwtAuthenticationFilter.java
  src/main/java/com/meme/ala/core/config/WebSecurityConfig.java
  src/main/java/com/meme/ala/core/error/ErrorCode.java
  src/main/java/com/meme/ala/core/error/ErrorResponse.java
  src/main/java/com/meme/ala/core/error/GlobalExceptionHandler.java
  src/main/java/com/meme/ala/core/error/exception/BusinessException.java
  src/main/java/com/meme/ala/core/error/exception/EntityNotFoundException.java
  src/main/java/com/meme/ala/core/error/exception/InvalidValueException.java
  src/main/java/com/meme/ala/domain/member/model/dto/MemberDto.java
  src/main/java/com/meme/ala/domain/member/model/entity/Member.java
  src/main/java/com/meme/ala/domain/member/model/mapper/MemberMapper.java
Labels: Chore

#14 Add: 기본 도메인 클래스 추가
  build.gradle
  src/main/java/com/meme/ala/domain/aggregation/model/entity/Aggregation.java
  src/main/java/com/meme/ala/domain/aggregation/model/entity/WordCount.java
  src/main/java/com/meme/ala/domain/alacard/model/entity/AlaCard.java
  src/main/java/com/meme/ala/domain/alacard/model/entity/MiddleCategory.java
  src/main/java/com/meme/ala/domain/alacard/model/entity/SentenceComponent.java
  src/main/java/com/meme/ala/domain/alacard/model/entity/Word.java
  src/main/java/com/meme/ala/domain/friend/model/entity/Friend.java
  src/main/java/com/meme/ala/domain/member/model/entity/Member.java
  src/main/java/com/meme/ala/domain/member/model/entity/MemberSetting.java
  src/main/java/com/meme/ala/domain/member/model/entity/cardSetting/AlaCardSetting.java
  src/main/java/com/meme/ala/domain/member/model/entity/cardSetting/Background.java
  src/main/java/com/meme/ala/domain/member/model/entity/cardSetting/Font.java
Labels: feature

#16 Feature 4/sociallogin
  src/main/java/com/meme/ala/core/auth/oauth/GoogleUser.java
  src/main/java/com/meme/ala/core/auth/oauth/NaverUser.java
  src/main/java/com/meme/ala/domain/aggregation/model/entity/Aggregation.java
  src/main/java/com/meme/ala/domain/aggregation/model/entity/WordCount.java
  src/main/java/com/meme/ala/domain/alacard/model/entity/AlaCard.java
  src/main/java/com/meme/ala/domain/alacard/model/entity/MiddleCategory.java
  src/main/java/com/meme/ala/domain/alacard/model/entity/SentenceComponent.java
  src/main/java/com/meme/ala/domain/alacard/model/entity/Word.java
  src/main/java/com/meme/ala/domain/friend/model/entity/Friend.java
  src/main/java/com/meme/ala/domain/member/model/entity/Member.java
  src/main/java/com/meme/ala/domain/member/model/entity/MemberSetting.java
  src/main/java/com/meme/ala/domain/member/model/entity/cardSetting/AlaCardSetting.java
  src/main/java/com/meme/ala/domain/member/model/entity/cardSetting/Background.java
  src/main/java/com/meme/ala/domain/member/model/entity/cardSetting/Font.java
  src/main/java/com/meme/ala/domain/member/service/MemberService.java
  src/main/java/com/meme/ala/domain/member/service/MemberServiceImpl.java
  src/test/java/com/meme/ala/domain/member/controller/MemberControllerTest.java
Labels: bug

#19 Feature 5/jwttoken
  build.gradle
  src/main/java/com/meme/ala/core/auth/jwt/Authority.java
  src/main/java/com/meme/ala/core/auth/jwt/JwtAuthenticationFilter.java
  src/main/java/com/meme/ala/core/auth/jwt/JwtTokenProvider.java
  src/main/java/com/meme/ala/core/auth/jwt/UserDetailServiceImpl.java
  src/main/java/com/meme/ala/core/auth/jwt/UserDetailsImpl.java
  src/main/java/com/meme/ala/core/config/WebSecurityConfig.java
  src/main/java/com/meme/ala/domain/member/controller/MemberController.java
  src/main/java/com/meme/ala/domain/member/model/entity/Member.java
  src/main/java/com/meme/ala/domain/member/service/MemberServiceImpl.java
  src/main/resources/application.properties
  src/test/java/com/meme/ala/core/auth/jwt/JwtTokenProviderTest.java
  src/test/java/com/meme/ala/domain/member/controller/MemberControllerTest.java
Labels: member

#44 Fix: Member 테스트 코드 MemberAuth로 수정
  build.gradle
  src/main/java/com/meme/ala/core/config/ApiDocumentUtils.java
  src/main/java/com/meme/ala/domain/alacard/model/entity/AlaCard.java
  src/test/java/com/meme/ala/core/auth/controller/MemberAuthControllerTest.java
  src/test/java/com/meme/ala/domain/member/controller/MemberControllerTest.java
Labels: Emergency

#50 Feat: 사용자 세팅 정보 수정 엔드포인트
  .github/workflows/gradle-test.yml
  .gitignore
  build.gradle
  src/docs/asciidoc/index.adoc
  src/main/java/com/meme/ala/common/annotation/CurrentUser.java
  src/main/java/com/meme/ala/domain/member/controller/MemberController.java
  src/main/java/com/meme/ala/domain/member/model/dto/MemberPrincipalDto.java
  src/main/java/com/meme/ala/domain/member/model/mapper/MemberMapper.java
  src/main/java/com/meme/ala/domain/member/service/MemberService.java
  src/main/java/com/meme/ala/domain/member/service/MemberServiceImpl.java
  src/main/resources/static/docs/html5/index.html
  src/main/resources/static/docs/index.html
  src/test/java/com/meme/ala/alacard/entity/AlaCardCreator.java
  src/test/java/com/meme/ala/common/DtoFactory.java
  src/test/java/com/meme/ala/common/EntityFactory.java
  src/test/java/com/meme/ala/core/config/WithUserDetailsSecurityContextFactory.java
  src/test/java/com/meme/ala/domain/member/controller/MemberControllerTest.java
  src/test/java/com/meme/ala/domain/member/entity/mapper/MemberMapperTest.java
  src/test/java/com/meme/ala/member/controller/MemberControllerTest.java
  src/test/java/com/meme/ala/member/entity/AlaCardSettingCreator.java
  src/test/java/com/meme/ala/member/entity/MemberCreator.java
  src/test/java/com/meme/ala/member/entity/MemberPrincipalDtoCreator.java
  src/test/java/com/meme/ala/member/mapper/MemberMapperTest.java
Labels: feature

#66 feature 30/read freinds
  src/docs/asciidoc/index.adoc
  src/main/java/com/meme/ala/common/message/ResponseMessage.java
  src/main/java/com/meme/ala/domain/friend/controller/FriendController.java
  src/main/java/com/meme/ala/domain/friend/model/dto/FriendDto.java
  src/main/java/com/meme/ala/domain/friend/model/entity/Friend.java
  src/main/java/com/meme/ala/domain/friend/model/mapper/FriendMapper.java
  src/main/java/com/meme/ala/domain/friend/repository/FriendRepository.java
  src/main/java/com/meme/ala/domain/friend/service/FriendService.java
  src/main/java/com/meme/ala/domain/friend/service/FriendServiceImpl.java
  src/main/java/com/meme/ala/domain/member/service/MemberService.java
  src/test/java/com/meme/ala/common/DtoFactory.java
  src/test/java/com/meme/ala/domain/friend/controller/FriendControllerTest.java
  src/test/java/com/meme/ala/domain/friend/entity/mapper/FriendMapperTest.java
Labels: feature

#70 Feature 68/bug map complex key
  src/main/java/com/meme/ala/domain/alacard/model/dto/request/AlaCardSaveDto.java
  src/main/java/com/meme/ala/domain/alacard/model/dto/request/MiddleCategoryDto.java
  src/main/java/com/meme/ala/domain/alacard/model/dto/request/WordDto.java
  src/main/java/com/meme/ala/domain/alacard/service/AlaCardServiceImpl.java
  src/main/java/com/meme/ala/domain/member/model/entity/AlaCardSettingPair.java
  src/main/java/com/meme/ala/domain/member/model/entity/Member.java
  src/main/java/com/meme/ala/domain/member/model/entity/cardSetting/AlaCardSetting.java
  src/main/java/com/meme/ala/domain/member/service/MemberCardService.java
  src/main/java/com/meme/ala/domain/member/service/MemberCardServiceImpl.java
  src/test/java/com/meme/ala/common/DtoFactory.java
  src/test/java/com/meme/ala/common/EntityFactory.java
  src/test/java/com/meme/ala/domain/member/service/MemberCardServiceTest.java
Labels: bug

#74 Feature73/background img
  src/main/java/com/meme/ala/domain/aggregation/model/entity/Aggregation.java
  src/main/java/com/meme/ala/domain/alacard/model/dto/response/AlaCardSettingDto.java
  src/main/java/com/meme/ala/domain/alacard/model/mapper/AlaCardSettingMapper.java
  src/main/java/com/meme/ala/domain/alacard/service/AlaCardServiceImpl.java
  src/main/java/com/meme/ala/domain/member/model/entity/cardSetting/Background.java
  src/test/java/com/meme/ala/common/DtoFactory.java
  src/test/java/com/meme/ala/common/EntityFactory.java
  src/test/java/com/meme/ala/domain/alacard/controller/AlaCardControllerTest.java
  src/test/java/com/meme/ala/domain/alacard/entity/mapper/AlaCardMapperTest.java
  src/test/java/com/meme/ala/domain/alacard/entity/mapper/AlaCardSettingMapperTest.java
Labels: bug

#72 Feature 32,33/add accept friend
  src/docs/asciidoc/index.adoc
  src/main/java/com/meme/ala/core/error/ErrorCode.java
  src/main/java/com/meme/ala/domain/friend/controller/FriendController.java
  src/main/java/com/meme/ala/domain/friend/model/entity/FriendInfo.java
  src/main/java/com/meme/ala/domain/friend/repository/FriendInfoRepository.java
  src/main/java/com/meme/ala/domain/friend/service/FriendService.java
  src/main/java/com/meme/ala/domain/friend/service/FriendServiceImpl.java
  src/test/java/com/meme/ala/common/EntityFactory.java
  src/test/java/com/meme/ala/domain/friend/controller/FriendControllerTest.java
  src/test/java/com/meme/ala/domain/friend/service/FriendServiceTest.java
Labels: feature, friend
