Repository dnd-side-project/dnd-5th-5-backend, pull requests merged in 2021-08, with the labels that each got.

#85 Feat: 친구 삭제 기능
  src/docs/asciidoc/index.adoc
  src/main/java/com/meme/ala/core/error/ErrorCode.java
  src/main/java/com/meme/ala/domain/friend/controller/FriendController.java
  src/main/java/com/meme/ala/domain/friend/service/FriendService.java
  src/main/java/com/meme/ala/domain/friend/service/FriendServiceImpl.java
  src/test/java/com/meme/ala/domain/friend/controller/FriendControllerTest.java
Labels: feature

#86 Feature 69/init friend info
  build.gradle
  src/main/java/com/meme/ala/AlaApplication.java
  src/main/java/com/meme/ala/core/annotation/PublishEvent.java
  src/main/java/com/meme/ala/core/aop/PublishEventAspect.java
  src/main/java/com/meme/ala/domain/event/component/EventHandler.java
  src/main/java/com/meme/ala/domain/event/model/entity/InitEvent.java
  src/main/java/com/meme/ala/domain/friend/service/FriendService.java
  src/main/java/com/meme/ala/domain/friend/service/FriendServiceImpl.java
  src/main/java/com/meme/ala/domain/member/service/MemberService.java
  src/main/java/com/meme/ala/domain/member/service/MemberServiceImpl.java
Labels: enhancement, feature

#88 hotfix/aop
  src/main/java/com/meme/ala/core/auth/controller/MemberAuthController.java
  src/main/java/com/meme/ala/core/auth/oauth/model/GoogleUser.java
  src/main/java/com/meme/ala/core/auth/oauth/model/NaverUser.java
  src/main/java/com/meme/ala/core/auth/oauth/model/OAuthProvider.java
  src/main/java/com/meme/ala/core/auth/oauth/model/OAuthUserInfo.java
  src/main/java/com/meme/ala/core/auth/oauth/service/OAuthService.java
  src/main/java/com/meme/ala/domain/member/repository/MemberRepository.java
  src/main/java/com/meme/ala/domain/member/service/MemberService.java
  src/main/java/com/meme/ala/domain/member/service/MemberServiceImpl.java
  src/test/java/com/meme/ala/core/auth/controller/MemberAuthControllerTest.java
Labels: Emergency, refactor

#89 Fix: initiailize 코드 aop initMember로 이동
  src/main/java/com/meme/ala/domain/event/component/EventHandler.java
  src/main/java/com/meme/ala/domain/member/service/MemberServiceImpl.java
Labels: Emergency

#91 Fix: getAlaCardDtoList 수정
  src/main/java/com/meme/ala/domain/alacard/service/AlaCardServiceImpl.java
Labels: Emergency

#93 Feature 59/duplicate word list
  src/main/java/com/meme/ala/domain/alacard/controller/AlaCardController.java
  src/main/java/com/meme/ala/domain/alacard/model/entity/TemporalWordList.java
  src/main/java/com/meme/ala/domain/alacard/model/mapper/AlaCardSaveMapper.java
  src/main/java/com/meme/ala/domain/alacard/repository/TemporalWordListRepository.java
  src/main/java/com/meme/ala/domain/alacard/service/AlaCardService.java
  src/main/java/com/meme/ala/domain/alacard/service/AlaCardServiceImpl.java
  src/main/java/com/meme/ala/domain/member/service/MemberCardService.java
  src/main/java/com/meme/ala/domain/member/service/MemberCardServiceImpl.java
  src/test/java/com/meme/ala/domain/alacard/controller/AlaCardControllerTest.java
Labels: alacard, feature

#99 Refactor: 쿠키 유틸 서비스 분리
  src/main/java/com/meme/ala/common/utils/CookieGenerator.java
  src/main/java/com/meme/ala/domain/alacard/controller/AlaCardController.java
Labels: enhancement

#123 Feature 121,122/friend relation and refactor entity
  src/main/java/com/meme/ala/common/message/ResponseMessage.java
  src/main/java/com/meme/ala/core/error/ErrorCode.java
  src/main/java/com/meme/ala/domain/event/component/EventHandler.java
  src/main/java/com/meme/ala/domain/friend/controller/FriendController.java
  src/main/java/com/meme/ala/domain/friend/model/dto/FriendRelationDto.java
  src/main/java/com/meme/ala/domain/friend/model/entity/FriendInfo.java
  src/main/java/com/meme/ala/domain/friend/model/entity/FriendRelation.java
  src/main/java/com/meme/ala/domain/friend/service/FriendInfoService.java
  src/main/java/com/meme/ala/domain/friend/service/FriendInfoServiceImpl.java
  src/main/java/com/meme/ala/domain/friend/service/FriendService.java
  src/main/java/com/meme/ala/domain/friend/service/FriendServiceImpl.java
  src/test/java/com/meme/ala/common/EntityFactory.java
  src/test/java/com/meme/ala/domain/friend/controller/FriendControllerTest.java
  src/test/java/com/meme/ala/domain/friend/service/FriendInfoServiceTest.java
Labels: enhancement, feature

#125 Feature 106, 107/cancel following_and_decline_friend
  src/docs/asciidoc/index.adoc
  src/main/java/com/meme/ala/common/message/ResponseMessage.java
  src/main/java/com/meme/ala/domain/friend/controller/FriendController.java
  src/main/java/com/meme/ala/domain/friend/service/FriendInfoService.java
  src/main/java/com/meme/ala/domain/friend/service/FriendInfoServiceImpl.java
  src/test/java/com/meme/ala/domain/friend/controller/FriendControllerTest.java
Labels: feature, friend

#127 Feat: 알람 저장 기능, 사용자별로 알람을 보여주는 기능
  src/docs/asciidoc/index.adoc
  src/main/java/com/meme/ala/domain/alarm/controller/AlarmController.java
  src/main/java/com/meme/ala/domain/alarm/model/dto/AlarmDto.java
  src/main/java/com/meme/ala/domain/alarm/model/entity/Alarm.java
  src/main/java/com/meme/ala/domain/alarm/model/entity/FriendAlarm.java
  src/main/java/com/meme/ala/domain/alarm/model/entity/NoticeAlarm.java
  src/main/java/com/meme/ala/domain/alarm/model/mapper/AlarmMapper.java
  src/main/java/com/meme/ala/domain/alarm/repository/AlarmRepository.java
  src/main/java/com/meme/ala/domain/alarm/service/AlarmService.java
  src/main/java/com/meme/ala/domain/alarm/service/AlarmServiceImpl.java
  src/main/java/com/meme/ala/domain/member/repository/MemberRepository.java
  src/main/java/com/meme/ala/domain/member/service/MemberService.java
  src/main/java/com/meme/ala/domain/member/service/MemberServiceImpl.java
  src/test/java/com/meme/ala/common/DtoFactory.java
  src/test/java/com/meme/ala/common/EntityFactory.java
  src/test/java/com/meme/ala/domain/alarm/controller/AlarmControllerTest.java
  src/test/java/com/meme/ala/domain/alarm/entity/mapper/AlarmMapperTest.java
  src/test/java/com/meme/ala/domain/member/entity/mapper/MemberMapperTest.java
Labels: feature, alarm

#145 Fix: 시큐리티 URI 설정
  src/main/java/com/meme/ala/core/auth/jwt/JwtAuthenticationEntryPoint.java
  src/main/java/com/meme/ala/core/auth/jwt/JwtAuthenticationFilter.java
  src/main/java/com/meme/ala/core/auth/jwt/JwtProvider.java
  src/main/java/com/meme/ala/core/config/WebSecurityConfig.java
  src/main/java/com/meme/ala/core/error/ErrorCode.java
  src/main/java/com/meme/ala/core/error/GlobalExceptionHandler.java
  src/main/java/com/meme/ala/domain/member/service/MemberCardServiceImpl.java
Labels: bug, Emergency, frontend

#156 Feat: special alacard
  src/main/java/com/meme/ala/domain/alacard/model/dto/request/AlaCardSaveDto.java
  src/main/java/com/meme/ala/domain/alacard/model/entity/AlaCard.java
  src/main/java/com/meme/ala/domain/alacard/model/mapper/AlaCardSaveMapper.java
  src/main/java/com/meme/ala/domain/member/service/MemberCardServiceImpl.java
Labels: alacard

#157 Feat: cors 설정
  src/main/java/com/meme/ala/core/config/WebConfig.java
Labels: Emergency, frontend

#158 Feat: v2로 wordlist 제공하는 api 추가
  src/docs/asciidoc/index.adoc
  src/main/java/com/meme/ala/domain/alacard/controller/AlaCardControllerV2.java
  src/test/java/com/meme/ala/domain/alacard/controller/AlaCardControllerV2Test.java
Labels: alacard, frontend

#161 Feat: follower list
  src/docs/asciidoc/index.adoc
  src/main/java/com/meme/ala/common/message/ResponseMessage.java
  src/main/java/com/meme/ala/domain/friend/controller/FriendController.java
  src/main/java/com/meme/ala/domain/friend/service/FriendInfoService.java
  src/main/java/com/meme/ala/domain/friend/service/FriendInfoServiceImpl.java
  src/test/java/com/meme/ala/domain/friend/controller/FriendControllerTest.java
Labels: feature, friend

#168 Feature 162/member info
  .gitignore
  src/docs/asciidoc/index.adoc
  src/main/java/com/meme/ala/domain/member/controller/MemberController.java
  src/test/java/com/meme/ala/domain/member/controller/MemberControllerTest.java
Labels: enhancement, feature

#171 Refactor: 카드 세팅 이미지 API data 수정
  src/main/java/com/meme/ala/domain/alacard/controller/AlaCardController.java
  src/main/java/com/meme/ala/domain/alacard/model/dto/response/BackgroundDtoInSetting.java
  src/main/java/com/meme/ala/domain/alacard/model/entity/cardSetting/Background.java
  src/main/java/com/meme/ala/domain/alacard/service/AlaCardService.java
  src/main/java/com/meme/ala/domain/alacard/service/AlaCardServiceImpl.java
  src/test/java/com/meme/ala/common/EntityFactory.java
  src/test/java/com/meme/ala/domain/alacard/controller/AlaCardControllerTest.java
Labels: enhancement, alacard

#176 Feat: jacoco를 통한 코드 커버리지 확인
  build.gradle
Labels: feature

#181 Feature 175/alacard event
  src/main/java/com/meme/ala/core/annotation/QuestCheck.java
  src/main/java/com/meme/ala/core/aop/QuestAspect.java
  src/main/java/com/meme/ala/core/error/ErrorCode.java
  src/main/java/com/meme/ala/domain/aggregation/service/AggregationService.java
  src/main/java/com/meme/ala/domain/aggregation/service/AggregationServiceImpl.java
  src/main/java/com/meme/ala/domain/alacard/service/AlaCardServiceImpl.java
  src/main/java/com/meme/ala/domain/event/component/EventHandler.java
  src/main/java/com/meme/ala/domain/event/model/entity/QuestEvent.java
  src/main/java/com/meme/ala/domain/quest/model/entity/EvaluationQuest.java
  src/main/java/com/meme/ala/domain/quest/model/entity/Quest.java
  src/main/java/com/meme/ala/domain/quest/model/entity/QuestCategory.java
  src/main/java/com/meme/ala/domain/quest/model/entity/QuestCondition.java
  src/main/java/com/meme/ala/domain/quest/repository/QuestRepository.java
  src/main/java/com/meme/ala/domain/quest/service/QuestConditionService.java
  src/main/java/com/meme/ala/domain/quest/service/QuestConditionServiceImpl.java
  src/main/java/com/meme/ala/domain/quest/service/QuestService.java
  src/main/java/com/meme/ala/domain/quest/service/QuestServiceImpl.java
  src/main/java/com/meme/ala/domain/quest/service/QuestStatusService.java
  src/main/java/com/meme/ala/domain/quest/service/QuestStatusServiceImpl.java
Labels: alacard, event
